In [1]:
import time

import torch
from torch import Tensor
torch.manual_seed(0)
from torch import nn
import torch.nn.functional as F
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
stdscaler = StandardScaler()

def closure():
        optimizer.zero_grad()
        y_hat = model.forward(X_train)
        loss = criterion(y_hat, y_train)
        loss.backward()
        return loss
    
from sklearn.preprocessing import LabelEncoder

LE = LabelEncoder()

import numpy as np
from sklearn.model_selection import GridSearchCV

from copy import deepcopy

data = pd.read_csv('Proj1ReorderedRound.csv')

import warnings
warnings.filterwarnings('ignore')

In [2]:
X = data.drop('Condition', axis=1).values
y = data['Condition'].values

y = LE.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
X_train = stdscaler.fit_transform(X_train)
X_test = stdscaler.transform(X_test)
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

In [3]:
class ANN(nn.Module):
    def __init__(self,solver, array):
        super().__init__()
        
        if (solver == 'SGD'):
            self.fc1 = nn.Linear(in_features = 12, out_features = array[0])
            self.output = nn.Linear(in_features=array[0], out_features=3)
            
        if (solver == 'LBFGS'):
            self.fc1 = nn.Linear(in_features = 12, out_features = array[0])
            self.fc2 = nn.Linear(in_features = array[0], out_features = array[1])
            self.output = nn.Linear(in_features=array[1], out_features=3)
        
        if (solver == 'Adam'):
            self.fc1 = nn.Linear(in_features = 12, out_features = array[0])
            self.fc2 = nn.Linear(in_features = array[0], out_features = array[1])
            self.fc3 = nn.Linear(in_features = array[1], out_features = array[2])
            self.output = nn.Linear(in_features=array[2], out_features=3)
            
        self.layers = len(array)
        
        self.solver = solver
 
    def forward(self, x):
        
        if (solver == 'SGD'):
            x = F.selu(self.fc1(x))
            x = self.output(x)
            
        if (solver == 'LBFGS'):
            x = F.relu(self.fc1(x))
            x = F.relu(self.fc2(x))
            x = self.output(x)
        
        if (solver == 'Adam'):
            x = F.selu(self.fc1(x))
            x = F.selu(self.fc2(x))
            x = F.selu(self.fc3(x))
            x = self.output(x)
        
        return x
    
alpha = 0.1
criterion = nn.CrossEntropyLoss()

In [4]:
initiator = 0

solver = 'Adam'         #choose solver here

if (solver == 'Adam'):
    af = 'selu'
    layers = 3

if (solver == 'LBFGS'):
    af = 'relu'
    layers = 2
    
if (solver == 'SGD'):
    af = 'selu'
    layers = 1


basename = ['i','j','k']
    
configDF = pd.DataFrame(columns = basename[:layers])
index = 0

for i in range(12):
    if (layers == 1):
        configDF.loc[index] = [i+1]
        
    for j in range(12):
        if (layers == 2):
            configDF.loc[index] = [i+1,j+1]
            
        for k in range(12):
            if (layers == 3):
                configDF.loc[index] = [i+1,j+1,k+1]
                
            index += 1
            
configDF.index = range(len(configDF))





print('Solver : ', solver)
print('Activation function : ', af)
print('# of hidden layers : ', layers)

configDF

Solver :  Adam
Activation function :  selu
# of hidden layers :  3


i   j   k
0      1   1   1
1      1   1   2
2      1   1   3
3      1   1   4
4      1   1   5
...   ..  ..  ..
1723  12  12   8
1724  12  12   9
1725  12  12  10
1726  12  12  11
1727  12  12  12

[1728 rows x 3 columns]

In [5]:
for index in configDF.index:
    Arr = configDF.loc[index].values
    print(Arr)

[1 1 1]
[1 1 2]
[1 1 3]
[1 1 4]
[1 1 5]
[1 1 6]
[1 1 7]
[1 1 8]
[1 1 9]
[1 1 10]
[1 1 11]
[1 1 12]
[1 2 1]
[1 2 2]
[1 2 3]
[1 2 4]
[1 2 5]
[1 2 6]
[1 2 7]
[1 2 8]
[1 2 9]
[1 2 10]
[1 2 11]
[1 2 12]
[1 3 1]
[1 3 2]
[1 3 3]
[1 3 4]
[1 3 5]
[1 3 6]
[1 3 7]
[1 3 8]
[1 3 9]
[1 3 10]
[1 3 11]
[1 3 12]
[1 4 1]
[1 4 2]
[1 4 3]
[1 4 4]
[1 4 5]
[1 4 6]
[1 4 7]
[1 4 8]
[1 4 9]
[1 4 10]
[1 4 11]
[1 4 12]
[1 5 1]
[1 5 2]
[1 5 3]
[1 5 4]
[1 5 5]
[1 5 6]
[1 5 7]
[1 5 8]
[1 5 9]
[1 5 10]
[1 5 11]
[1 5 12]
[1 6 1]
[1 6 2]
[1 6 3]
[1 6 4]
[1 6 5]
[1 6 6]
[1 6 7]
[1 6 8]
[1 6 9]
[1 6 10]
[1 6 11]
[1 6 12]
[1 7 1]
[1 7 2]
[1 7 3]
[1 7 4]
[1 7 5]
[1 7 6]
[1 7 7]
[1 7 8]
[1 7 9]
[1 7 10]
[1 7 11]
[1 7 12]
[1 8 1]
[1 8 2]
[1 8 3]
[1 8 4]
[1 8 5]
[1 8 6]
[1 8 7]
[1 8 8]
[1 8 9]
[1 8 10]
[1 8 11]
[1 8 12]
[1 9 1]
[1 9 2]
[1 9 3]
[1 9 4]
[1 9 5]
[1 9 6]
[1 9 7]
[1 9 8]
[1 9 9]
[1 9 10]
[1 9 11]
[1 9 12]
[1 10 1]
[1 10 2]
[1 10 3]
[1 10 4]
[1 10 5]
[1 10 6]
[1 10 7]
[1 10 8]
[1 10 9]
[1 10 10]
[1 10 11]
[1 10 12

[11 1 6]
[11 1 7]
[11 1 8]
[11 1 9]
[11 1 10]
[11 1 11]
[11 1 12]
[11 2 1]
[11 2 2]
[11 2 3]
[11 2 4]
[11 2 5]
[11 2 6]
[11 2 7]
[11 2 8]
[11 2 9]
[11 2 10]
[11 2 11]
[11 2 12]
[11 3 1]
[11 3 2]
[11 3 3]
[11 3 4]
[11 3 5]
[11 3 6]
[11 3 7]
[11 3 8]
[11 3 9]
[11 3 10]
[11 3 11]
[11 3 12]
[11 4 1]
[11 4 2]
[11 4 3]
[11 4 4]
[11 4 5]
[11 4 6]
[11 4 7]
[11 4 8]
[11 4 9]
[11 4 10]
[11 4 11]
[11 4 12]
[11 5 1]
[11 5 2]
[11 5 3]
[11 5 4]
[11 5 5]
[11 5 6]
[11 5 7]
[11 5 8]
[11 5 9]
[11 5 10]
[11 5 11]
[11 5 12]
[11 6 1]
[11 6 2]
[11 6 3]
[11 6 4]
[11 6 5]
[11 6 6]
[11 6 7]
[11 6 8]
[11 6 9]
[11 6 10]
[11 6 11]
[11 6 12]
[11 7 1]
[11 7 2]
[11 7 3]
[11 7 4]
[11 7 5]
[11 7 6]
[11 7 7]
[11 7 8]
[11 7 9]
[11 7 10]
[11 7 11]
[11 7 12]
[11 8 1]
[11 8 2]
[11 8 3]
[11 8 4]
[11 8 5]
[11 8 6]
[11 8 7]
[11 8 8]
[11 8 9]
[11 8 10]
[11 8 11]
[11 8 12]
[11 9 1]
[11 9 2]
[11 9 3]
[11 9 4]
[11 9 5]
[11 9 6]
[11 9 7]
[11 9 8]
[11 9 9]
[11 9 10]
[11 9 11]
[11 9 12]
[11 10 1]
[11 10 2]
[11 10 3]
[11 10 4]
[11 10

In [6]:
time_list = []

epochs = 100

LossDF = pd.DataFrame(columns = ['config','nodes','initial','midway','final','last change'])

if (initiator == 0):    #checks if this cell has been run before...
    FML = []   # Full Model List : stores initial model weights and bias for future reference
      
for index in configDF.index:
    Start = time.time()     #start time
    to_add = []
    
    Arr = configDF.loc[index].values
    to_add.append(Arr)
    to_add.append(configDF.loc[index].sum())
    
    if (initiator == 0):        # if this cell wasnt run before, store the starting weights and bias for future ref
        model = ANN(solver,Arr)
        dummy = deepcopy(model)
        FML.append(dummy)
        
    elif (initiator == 1):      # otherwise, use the same starting params...
        model = deepcopy(FML[index])
        setattr(model, 'array', Arr)    #... while overwriting the hidden layer configuration
        
    if (solver == 'Adam'):
        optimizer = torch.optim.Adam(model.parameters(), lr=alpha) # ADAM
    if (solver == 'LBFGS'):
        optimizer = torch.optim.LBFGS(model.parameters(), lr=alpha) # LBFGS
    if (solver == 'SGD'):
        optimizer = torch.optim.SGD(model.parameters(), lr=alpha) # SGD
    
    for e in range(epochs):
        y_hat = model.forward(X_train)
        loss = criterion(y_hat, y_train)
                
        if e == 0:
            to_add.append(loss.detach().numpy())
                    
        if e == 49:
            to_add.append(loss.detach().numpy())
 
        optimizer.zero_grad()
        loss.backward()
             
        if (solver == 'LBFGS'):
            optimizer.step(closure)
            
        else:
            optimizer.step()
        
        if e == 98:
            A = loss.detach().numpy()
            
        if e == 99:
            B = loss.detach().numpy()
            
    to_add.append(loss.detach().numpy())
    to_add.append(B-A)
            
    LossDF.loc[index] = to_add
    
    End = time.time()
    dura = End - Start
    time_list.append(dura)
    
    print('\nComputation for',Arr,'complete')
    print('Time taken : ', np.round(dura,3),'s')

initiator = 1

print('\nSolver : ', solver)
print('# of hidden layers :', layers)
print('Activation function : ', af)
print('Epochs : ', epochs)

print('\nTotal time taken :',np.round(np.sum(time_list),3),'s')

print('average loss = ', np.round(LossDF.mean()[-2],5))
print('average loss (without ones) = ', np.round(LossDF.drop(0).mean()[-2],5))

LossDF


Computation for [1 1 1] complete
Time taken :  0.118 s

Computation for [1 1 2] complete
Time taken :  0.092 s

Computation for [1 1 3] complete
Time taken :  0.096 s

Computation for [1 1 4] complete
Time taken :  0.092 s

Computation for [1 1 5] complete
Time taken :  0.1 s

Computation for [1 1 6] complete
Time taken :  0.09 s

Computation for [1 1 7] complete
Time taken :  0.093 s

Computation for [1 1 8] complete
Time taken :  0.091 s

Computation for [1 1 9] complete
Time taken :  0.098 s

Computation for [1 1 10] complete
Time taken :  0.094 s

Computation for [1 1 11] complete
Time taken :  0.098 s

Computation for [1 1 12] complete
Time taken :  0.104 s

Computation for [1 2 1] complete
Time taken :  0.091 s

Computation for [1 2 2] complete
Time taken :  0.09 s

Computation for [1 2 3] complete
Time taken :  0.1 s

Computation for [1 2 4] complete
Time taken :  0.093 s

Computation for [1 2 5] complete
Time taken :  0.095 s

Computation for [1 2 6] complete
Time taken :  0.0


Computation for [2 1 3] complete
Time taken :  0.099 s

Computation for [2 1 4] complete
Time taken :  0.091 s

Computation for [2 1 5] complete
Time taken :  0.09 s

Computation for [2 1 6] complete
Time taken :  0.093 s

Computation for [2 1 7] complete
Time taken :  0.09 s

Computation for [2 1 8] complete
Time taken :  0.093 s

Computation for [2 1 9] complete
Time taken :  0.101 s

Computation for [2 1 10] complete
Time taken :  0.095 s

Computation for [2 1 11] complete
Time taken :  0.103 s

Computation for [2 1 12] complete
Time taken :  0.097 s

Computation for [2 2 1] complete
Time taken :  0.091 s

Computation for [2 2 2] complete
Time taken :  0.093 s

Computation for [2 2 3] complete
Time taken :  0.096 s

Computation for [2 2 4] complete
Time taken :  0.096 s

Computation for [2 2 5] complete
Time taken :  0.095 s

Computation for [2 2 6] complete
Time taken :  0.095 s

Computation for [2 2 7] complete
Time taken :  0.093 s

Computation for [2 2 8] complete
Time taken : 


Computation for [3 1 5] complete
Time taken :  0.102 s

Computation for [3 1 6] complete
Time taken :  0.104 s

Computation for [3 1 7] complete
Time taken :  0.102 s

Computation for [3 1 8] complete
Time taken :  0.096 s

Computation for [3 1 9] complete
Time taken :  0.106 s

Computation for [3 1 10] complete
Time taken :  0.099 s

Computation for [3 1 11] complete
Time taken :  0.11 s

Computation for [3 1 12] complete
Time taken :  0.107 s

Computation for [3 2 1] complete
Time taken :  0.095 s

Computation for [3 2 2] complete
Time taken :  0.098 s

Computation for [3 2 3] complete
Time taken :  0.092 s

Computation for [3 2 4] complete
Time taken :  0.097 s

Computation for [3 2 5] complete
Time taken :  0.109 s

Computation for [3 2 6] complete
Time taken :  0.094 s

Computation for [3 2 7] complete
Time taken :  0.104 s

Computation for [3 2 8] complete
Time taken :  0.096 s

Computation for [3 2 9] complete
Time taken :  0.1 s

Computation for [3 2 10] complete
Time taken : 


Computation for [4 1 7] complete
Time taken :  0.1 s

Computation for [4 1 8] complete
Time taken :  0.106 s

Computation for [4 1 9] complete
Time taken :  0.101 s

Computation for [4 1 10] complete
Time taken :  0.104 s

Computation for [4 1 11] complete
Time taken :  0.093 s

Computation for [4 1 12] complete
Time taken :  0.105 s

Computation for [4 2 1] complete
Time taken :  0.109 s

Computation for [4 2 2] complete
Time taken :  0.094 s

Computation for [4 2 3] complete
Time taken :  0.104 s

Computation for [4 2 4] complete
Time taken :  0.098 s

Computation for [4 2 5] complete
Time taken :  0.096 s

Computation for [4 2 6] complete
Time taken :  0.096 s

Computation for [4 2 7] complete
Time taken :  0.099 s

Computation for [4 2 8] complete
Time taken :  0.098 s

Computation for [4 2 9] complete
Time taken :  0.107 s

Computation for [4 2 10] complete
Time taken :  0.098 s

Computation for [4 2 11] complete
Time taken :  0.104 s

Computation for [4 2 12] complete
Time taken


Computation for [5 1 11] complete
Time taken :  0.101 s

Computation for [5 1 12] complete
Time taken :  0.104 s

Computation for [5 2 1] complete
Time taken :  0.108 s

Computation for [5 2 2] complete
Time taken :  0.097 s

Computation for [5 2 3] complete
Time taken :  0.101 s

Computation for [5 2 4] complete
Time taken :  0.103 s

Computation for [5 2 5] complete
Time taken :  0.098 s

Computation for [5 2 6] complete
Time taken :  0.108 s

Computation for [5 2 7] complete
Time taken :  0.118 s

Computation for [5 2 8] complete
Time taken :  0.109 s

Computation for [5 2 9] complete
Time taken :  0.142 s

Computation for [5 2 10] complete
Time taken :  0.139 s

Computation for [5 2 11] complete
Time taken :  0.129 s

Computation for [5 2 12] complete
Time taken :  0.135 s

Computation for [5 3 1] complete
Time taken :  0.12 s

Computation for [5 3 2] complete
Time taken :  0.114 s

Computation for [5 3 3] complete
Time taken :  0.115 s

Computation for [5 3 4] complete
Time taken


Computation for [6 2 3] complete
Time taken :  0.102 s

Computation for [6 2 4] complete
Time taken :  0.102 s

Computation for [6 2 5] complete
Time taken :  0.107 s

Computation for [6 2 6] complete
Time taken :  0.1 s

Computation for [6 2 7] complete
Time taken :  0.1 s

Computation for [6 2 8] complete
Time taken :  0.1 s

Computation for [6 2 9] complete
Time taken :  0.101 s

Computation for [6 2 10] complete
Time taken :  0.106 s

Computation for [6 2 11] complete
Time taken :  0.108 s

Computation for [6 2 12] complete
Time taken :  0.103 s

Computation for [6 3 1] complete
Time taken :  0.097 s

Computation for [6 3 2] complete
Time taken :  0.1 s

Computation for [6 3 3] complete
Time taken :  0.1 s

Computation for [6 3 4] complete
Time taken :  0.107 s

Computation for [6 3 5] complete
Time taken :  0.101 s

Computation for [6 3 6] complete
Time taken :  0.105 s

Computation for [6 3 7] complete
Time taken :  0.106 s

Computation for [6 3 8] complete
Time taken :  0.104 s


Computation for [7 2 5] complete
Time taken :  0.104 s

Computation for [7 2 6] complete
Time taken :  0.111 s

Computation for [7 2 7] complete
Time taken :  0.099 s

Computation for [7 2 8] complete
Time taken :  0.109 s

Computation for [7 2 9] complete
Time taken :  0.107 s

Computation for [7 2 10] complete
Time taken :  0.115 s

Computation for [7 2 11] complete
Time taken :  0.116 s

Computation for [7 2 12] complete
Time taken :  0.11 s

Computation for [7 3 1] complete
Time taken :  0.1 s

Computation for [7 3 2] complete
Time taken :  0.096 s

Computation for [7 3 3] complete
Time taken :  0.104 s

Computation for [7 3 4] complete
Time taken :  0.096 s

Computation for [7 3 5] complete
Time taken :  0.099 s

Computation for [7 3 6] complete
Time taken :  0.1 s

Computation for [7 3 7] complete
Time taken :  0.102 s

Computation for [7 3 8] complete
Time taken :  0.115 s

Computation for [7 3 9] complete
Time taken :  0.105 s

Computation for [7 3 10] complete
Time taken :  0


Computation for [8 2 8] complete
Time taken :  0.1 s

Computation for [8 2 9] complete
Time taken :  0.105 s

Computation for [8 2 10] complete
Time taken :  0.108 s

Computation for [8 2 11] complete
Time taken :  0.103 s

Computation for [8 2 12] complete
Time taken :  0.1 s

Computation for [8 3 1] complete
Time taken :  0.099 s

Computation for [8 3 2] complete
Time taken :  0.097 s

Computation for [8 3 3] complete
Time taken :  0.105 s

Computation for [8 3 4] complete
Time taken :  0.101 s

Computation for [8 3 5] complete
Time taken :  0.106 s

Computation for [8 3 6] complete
Time taken :  0.114 s

Computation for [8 3 7] complete
Time taken :  0.102 s

Computation for [8 3 8] complete
Time taken :  0.102 s

Computation for [8 3 9] complete
Time taken :  0.101 s

Computation for [8 3 10] complete
Time taken :  0.102 s

Computation for [8 3 11] complete
Time taken :  0.102 s

Computation for [8 3 12] complete
Time taken :  0.105 s

Computation for [8 4 1] complete
Time taken :


Computation for [9 2 10] complete
Time taken :  0.11 s

Computation for [9 2 11] complete
Time taken :  0.103 s

Computation for [9 2 12] complete
Time taken :  0.112 s

Computation for [9 3 1] complete
Time taken :  0.1 s

Computation for [9 3 2] complete
Time taken :  0.108 s

Computation for [9 3 3] complete
Time taken :  0.103 s

Computation for [9 3 4] complete
Time taken :  0.112 s

Computation for [9 3 5] complete
Time taken :  0.102 s

Computation for [9 3 6] complete
Time taken :  0.109 s

Computation for [9 3 7] complete
Time taken :  0.105 s

Computation for [9 3 8] complete
Time taken :  0.114 s

Computation for [9 3 9] complete
Time taken :  0.112 s

Computation for [9 3 10] complete
Time taken :  0.111 s

Computation for [9 3 11] complete
Time taken :  0.113 s

Computation for [9 3 12] complete
Time taken :  0.102 s

Computation for [9 4 1] complete
Time taken :  0.109 s

Computation for [9 4 2] complete
Time taken :  0.099 s

Computation for [9 4 3] complete
Time taken 


Computation for [10 2 11] complete
Time taken :  0.104 s

Computation for [10 2 12] complete
Time taken :  0.103 s

Computation for [10 3 1] complete
Time taken :  0.103 s

Computation for [10 3 2] complete
Time taken :  0.099 s

Computation for [10 3 3] complete
Time taken :  0.102 s

Computation for [10 3 4] complete
Time taken :  0.101 s

Computation for [10 3 5] complete
Time taken :  0.109 s

Computation for [10 3 6] complete
Time taken :  0.102 s

Computation for [10 3 7] complete
Time taken :  0.101 s

Computation for [10 3 8] complete
Time taken :  0.107 s

Computation for [10 3 9] complete
Time taken :  0.11 s

Computation for [10 3 10] complete
Time taken :  0.107 s

Computation for [10 3 11] complete
Time taken :  0.105 s

Computation for [10 3 12] complete
Time taken :  0.106 s

Computation for [10 4 1] complete
Time taken :  0.101 s

Computation for [10 4 2] complete
Time taken :  0.107 s

Computation for [10 4 3] complete
Time taken :  0.113 s

Computation for [10 4 4] c


Computation for [11 2 10] complete
Time taken :  0.107 s

Computation for [11 2 11] complete
Time taken :  0.113 s

Computation for [11 2 12] complete
Time taken :  0.11 s

Computation for [11 3 1] complete
Time taken :  0.105 s

Computation for [11 3 2] complete
Time taken :  0.103 s

Computation for [11 3 3] complete
Time taken :  0.107 s

Computation for [11 3 4] complete
Time taken :  0.1 s

Computation for [11 3 5] complete
Time taken :  0.104 s

Computation for [11 3 6] complete
Time taken :  0.111 s

Computation for [11 3 7] complete
Time taken :  0.106 s

Computation for [11 3 8] complete
Time taken :  0.114 s

Computation for [11 3 9] complete
Time taken :  0.115 s

Computation for [11 3 10] complete
Time taken :  0.104 s

Computation for [11 3 11] complete
Time taken :  0.114 s

Computation for [11 3 12] complete
Time taken :  0.108 s

Computation for [11 4 1] complete
Time taken :  0.112 s

Computation for [11 4 2] complete
Time taken :  0.1 s

Computation for [11 4 3] comp


Computation for [12 2 9] complete
Time taken :  0.109 s

Computation for [12 2 10] complete
Time taken :  0.117 s

Computation for [12 2 11] complete
Time taken :  0.106 s

Computation for [12 2 12] complete
Time taken :  0.103 s

Computation for [12 3 1] complete
Time taken :  0.109 s

Computation for [12 3 2] complete
Time taken :  0.104 s

Computation for [12 3 3] complete
Time taken :  0.1 s

Computation for [12 3 4] complete
Time taken :  0.104 s

Computation for [12 3 5] complete
Time taken :  0.105 s

Computation for [12 3 6] complete
Time taken :  0.106 s

Computation for [12 3 7] complete
Time taken :  0.106 s

Computation for [12 3 8] complete
Time taken :  0.111 s

Computation for [12 3 9] complete
Time taken :  0.11 s

Computation for [12 3 10] complete
Time taken :  0.112 s

Computation for [12 3 11] complete
Time taken :  0.115 s

Computation for [12 3 12] complete
Time taken :  0.107 s

Computation for [12 4 1] complete
Time taken :  0.102 s

Computation for [12 4 2] co

config nodes    initial          midway          final  \
0        [1, 1, 1]     3  1.2169077      0.09128688    0.061185714   
1        [1, 1, 2]     4  1.1809545     0.043269914    0.008466022   
2        [1, 1, 3]     5  1.2876742     0.035740696    0.014210967   
3        [1, 1, 4]     6  1.1308988       0.0374758   0.0031749979   
4        [1, 1, 5]     7  1.1068028     0.038148884   0.0029495957   
...            ...   ...        ...             ...            ...   
1723   [12, 12, 8]    32  1.1853632   4.5102865e-06  1.4946817e-06   
1724   [12, 12, 9]    33  1.1056955   1.8969515e-06   7.759952e-07   
1725  [12, 12, 10]    34   1.106602  1.08003715e-05  2.8941247e-06   
1726  [12, 12, 11]    35  1.0915433    6.270665e-05   6.629613e-06   
1727  [12, 12, 12]    36    1.09785   2.2103974e-05   3.448998e-06   

       last change  
0     6.048907e-03  
1    -2.414798e-04  
2    -2.402877e-04  
3    -5.641580e-05  
4    -5.880813e-05  
...            ...  
1723 -1.604701e-08  
1724 -8.023278e-09  
1725 -2.979982e-08  
1726 -7.908284e-08  
1727 -6.074924e-08  

[1728 rows x 6 columns]

In [7]:
LossDF.dropna().sort_values(by = 'final', ascending = True)

config nodes    initial          midway          final  \
1053   [8, 4, 10]    22  1.1724633   3.5533517e-08  2.5217341e-08   
1099    [8, 8, 8]    24  1.1221968   1.5015733e-07  2.8656062e-08   
1672   [12, 8, 5]    25  1.1175213  1.26086706e-08  2.9802285e-08   
683    [5, 9, 12]    26  1.1458256    3.702338e-07  3.2094793e-08   
1324   [10, 3, 5]    18  1.1316986    1.398407e-07   4.470339e-08   
...           ...   ...        ...             ...            ...   
1548  [11, 10, 1]    22  1.1328155      0.45727718     0.48798436   
1356   [10, 6, 1]    17   1.327388      0.49336857     0.49049062   
1212    [9, 6, 1]    16  1.3214781      0.49327552     0.49107978   
1500   [11, 6, 1]    18  1.2328261      0.49351886      0.4931536   
1428  [10, 12, 1]    23  1.3642846       0.4936427      0.4933236   

       last change  
1053  0.000000e+00  
1099 -1.146242e-09  
1672  0.000000e+00  
683   0.000000e+00  
1324 -1.146233e-09  
...            ...  
1548 -8.109540e-02  
1356 -5.701184e-05  
1212  3.095567e-04  
1500 -2.294779e-06  
1428 -9.119511e-06  

[1728 rows x 6 columns]

In [8]:
LossDF.dropna().sort_values(by = 'last change', ascending = False)

config nodes    initial       midway        final  last change
1163   [9, 1, 12]    22   1.149263   0.04530354   0.15017709     0.022011
564    [4, 12, 1]    17  1.0983272  0.060089167   0.12245596     0.017963
948     [7, 8, 1]    16  1.3591495   0.45737344   0.44016644     0.015021
504     [4, 7, 1]    12   1.508817    0.4821718    0.2682622     0.009612
816     [6, 9, 1]    16  1.4474313   0.47571245   0.10784437     0.008683
...           ...   ...        ...          ...          ...          ...
912     [7, 5, 1]    13  1.0751897   0.48322356    0.2080195    -0.034485
1668   [12, 8, 1]    21   1.166259  0.055104014  0.067188606    -0.056036
1548  [11, 10, 1]    22  1.1328155   0.45727718   0.48798436    -0.081095
216     [2, 7, 1]    10  1.2859274    0.1272762   0.11223864    -0.091139
1116   [8, 10, 1]    19  1.1221383  0.046994608  0.026298128    -0.103695

[1728 rows x 6 columns]